#pragma once

// Name: DBZKakarot, Version: 1.0.3


/*!!DEFINE!!*/

/*!!HELPER_DEF!!*/

/*!!HELPER_INC!!*/

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace CG
{
//---------------------------------------------------------------------------
// Parameters
//---------------------------------------------------------------------------

// Function A_Player_Animation.A_Player_Animation_C.Hurt
struct UA_Player_Animation_C_Hurt_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_B0B870B746BC4C3EB46282851BEA6CA0
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_B0B870B746BC4C3EB46282851BEA6CA0_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_B7AA66984FE7F0976F40FB9626691481
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_B7AA66984FE7F0976F40FB9626691481_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_D7725B124927F4DB69D466922485714B
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_D7725B124927F4DB69D466922485714B_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_56743596495A971A1C85CFBB3BB19B01
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_56743596495A971A1C85CFBB3BB19B01_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_0FB0C7F04222A563F3CD7C83F1DC6987
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_0FB0C7F04222A563F3CD7C83F1DC6987_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_BlendSpacePlayer_D39BB1C3460DBFB8FC9F819771AD9EEE
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_BlendSpacePlayer_D39BB1C3460DBFB8FC9F819771AD9EEE_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_05A370C64205AA83B05138BE7E2CC6C1
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_05A370C64205AA83B05138BE7E2CC6C1_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_LayeredBoneBlend_12F6C9374BB5951724B662A6C4344F53
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_LayeredBoneBlend_12F6C9374BB5951724B662A6C4344F53_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_D70ECF92476BBF0FFCB384A39E5F4978
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_D70ECF92476BBF0FFCB384A39E5F4978_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_093A8B4649B936853EE1FF9690B1BCA4
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_093A8B4649B936853EE1FF9690B1BCA4_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_B3A4E5C2400ACED7B061528744C78FC0
struct UA_Player_Animation_C_EvaluateGraphExposedInputs_ExecuteUbergraph_A_Player_Animation_AnimGraphNode_TransitionResult_B3A4E5C2400ACED7B061528744C78FC0_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.BlueprintInitializeAnimation
struct UA_Player_Animation_C_BlueprintInitializeAnimation_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.AnimNotify_step
struct UA_Player_Animation_C_AnimNotify_step_Params
{
};

// Function A_Player_Animation.A_Player_Animation_C.ExecuteUbergraph_A_Player_Animation
struct UA_Player_Animation_C_ExecuteUbergraph_A_Player_Animation_Params
{
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
